/* Shared two-player camera arcade. Every game below has its own rules and
   visual language, but the input contract stays friendly: WASD vs arrows,
   pointer/touch on each half of the board, and optional two-hand tracking. */
const $=s=>document.querySelector(s), clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), rnd=(a,b)=>a+Math.random()*(b-a), pick=a=>a[Math.floor(Math.random()*a.length)];
const G={
  pong:{title:'PONG DUEL',tag:'Classic paddles. Modern hands. First to seven points takes the court.',kicker:'ATARI-STYLE TABLE',theme:['#e8e0ff','#17132d','#62e7ff','#ff5d9e'],hint:'Move your hand or paddle up and down. First to 7.',button:'START MATCH',keys:['P1  W / S','P2  ↑ / ↓']},
  cut:{title:'ROPE SNATCH',tag:'Cut the rope before the candy drops. Steal points from the other side.',kicker:'CUT-THE-ROPE REMIX',theme:['#fff0dc','#391b27','#ff6b45','#57d6a2'],hint:'Slice the candy with a click, tap, or SPACE / ENTER.',button:'CUT IN',keys:['P1  SPACE','P2  ENTER']},
  flappy:{title:'FLAPPY FACE-OFF',tag:'One tap, one flap, one very unforgiving pipe. Keep your bird alive longer.',kicker:'PIPE RACE',theme:['#c9f3ff','#12334a','#ffcf33','#ff705d'],hint:'Flap with SPACE / ENTER or tap your side.',button:'FLAP TO START',keys:['P1  SPACE','P2  ENTER']},
  subway:{title:'LANE DASH',tag:'Dodge the rush, switch lanes, and reach the finish before your rival.',kicker:'ENDLESS RUNNER',theme:['#ffe45c','#142b50','#f04c42','#6ce0d2'],hint:'A/D and ←/→ change lanes. Survive 45 seconds.',button:'RUN THE LINE',keys:['P1  A / D','P2  ← / →']},
  angry:{title:'BIRD BRAWL',tag:'Load the sling, aim at the piggies, and clear your half first.',kicker:'SLINGSHOT SHOWDOWN',theme:['#b8ecab','#2a3b23','#ed4f4f','#ffcf33'],hint:'Move the reticle, then fire with SPACE / ENTER.',button:'PULL BACK',keys:['P1  WASD + SPACE','P2  ARROWS + ENTER']},
  tetris:{title:'STACK ATTACK',tag:'Retro blocks, split-screen pressure. Clear lines to send junk across the divide.',kicker:'BLOCK PARTY // 1984',theme:['#202438','#f8f1d5','#7cf4e8','#f064a6'],hint:'A/D or arrows move; W / ↑ rotates; SPACE / ENTER drops.',button:'DROP BLOCKS',keys:['P1  W A S D','P2  ↑ ← ↓ →']},
  space:{title:'INVADER DUEL',tag:'Two ships. One sky. Shoot the fleet before the other pilot does.',kicker:'ARCADE SHOOTER',theme:['#090b16','#f3f0d0','#79f27c','#ff5f67'],hint:'Move sideways and fire with SPACE / ENTER.',button:'DEFEND EARTH',keys:['P1  A / D + SPACE','P2  ← / → + ENTER']},
  kart:{title:'KART CLASH',tag:'Drift through traffic, grab boosts, and cross the checkered line first.',kicker:'SPLIT-SCREEN RACER',theme:['#e7f0ff','#1d2a50','#ff5363','#ffd44a'],hint:'Steer left and right. Tap to boost through hazards.',button:'LIGHT THE GRID',keys:['P1  A / D + SPACE','P2  ← / → + ENTER']},
  whack:{title:'MOLE MAYHEM',tag:'Targets pop up on both sides. Hit yours, then steal the golden bonus.',kicker:'WHACK-IT DUEL',theme:['#d9f1bd','#263b24','#b05dff','#ffcf33'],hint:'Point and click your half, or use SPACE / ENTER.',button:'WHACK IN',keys:['P1  SPACE / CLICK','P2  ENTER / CLICK']},
  pacman:{title:'DOT DUEL',tag:'Clear the maze, dodge the ghosts, and eat more dots than your rival.',kicker:'MAZE CHOMP',theme:['#111533','#ffe04e','#5b8cff','#ff5c85'],hint:'WASD vs arrows. Collect every dot before the clock runs out.',button:'CHOMP ON',keys:['P1  WASD','P2  ARROWS']},
  doodle:{title:'DOODLE DROP',tag:'Bounce forever, land on the platforms, and climb higher than the other doodler.',kicker:'VERTICAL JUMPER',theme:['#bde8ff','#203252','#ff7c9b','#ffe36a'],hint:'Steer left and right. Auto-jump does the rest.',button:'START CLIMB',keys:['P1  A / D','P2  ← / →']},
  crossy:{title:'CROSSY CLASH',tag:'Cross the road five times without becoming pixel roadkill.',kicker:'ROAD-CROSSING RACE',theme:['#dff0d2','#213b2b','#f5a83b','#e95f62'],hint:'Move with WASD or arrows. First to five crossings wins.',button:'CROSS THE ROAD',keys:['P1  WASD','P2  ARROWS']},
  stack:{title:'STACK IT',tag:'Time the drop and build the tallest tower. Miss too far and the tower shrinks.',kicker:'PERFECT DROP',theme:['#ff7562','#301b29','#fbe36a','#69d2ff'],hint:'Tap SPACE / ENTER when the moving block lines up.',button:'BUILD TOWERS',keys:['P1  SPACE','P2  ENTER']},
  geometry:{title:'GEOMETRY RUSH',tag:'Jump the spikes, chase the beat, and keep your little square alive.',kicker:'ONE-BUTTON RUNNER',theme:['#101828','#f4f2e5','#ffcf33','#53e5d3'],hint:'Jump with SPACE / ENTER. The floor never stops moving.',button:'RUSH',keys:['P1  SPACE','P2  ENTER']},
  helix:{title:'HELIX FALL',tag:'Rotate around the gaps and drop deeper than your opponent.',kicker:'SPIRAL DROP',theme:['#31204a','#fff2db','#ff6d9b','#6de0d2'],hint:'Move left/right to rotate your ball around each ring.',button:'DROP IN',keys:['P1  A / D','P2  ← / →']},
  bomber:{title:'BOMBER DUEL',tag:'Plant a bomb, hide behind a wall, and trap the other player.',kicker:'GRID BLAST',theme:['#f3b08d','#241724','#ffdf4e','#67d8ce'],hint:'WASD vs arrows; SPACE / ENTER plants a bomb.',button:'LIGHT THE FUSE',keys:['P1  WASD + SPACE','P2  ARROWS + ENTER']},
  connect:{title:'FOUR IN A ROW',tag:'Drop discs, make a line, and jam the other player before they jam you.',kicker:'TABLETOP THROW-DOWN',theme:['#7fc8ff','#13284d','#f1525d','#f8d44e'],hint:'Choose a column with A/D or ←/→, then drop.',button:'DROP DISCS',keys:['P1  A/D + SPACE','P2  ←/→ + ENTER']},
  brawl:{title:'BRAWL SHOTS',tag:'Aim, dodge, and land five clean hits in this tiny arena brawler.',kicker:'TOP-DOWN ARENA',theme:['#ffb34f','#271d3b','#5a8cff','#ff5e7d'],hint:'Move, aim with the pointer, and fire with SPACE / ENTER.',button:'BRAWL',keys:['P1  WASD + SPACE','P2  ARROWS + ENTER']},
  party:{title:'PARTY MIX',tag:'A rapid-fire set of tiny camera-ready challenges. First to seven wins.',kicker:'MINIGAME MIX',theme:['#ff9cdb','#321641','#ffe15b','#65e6c7'],hint:'Follow the prompt: match, react, or tap your target.',button:'START PARTY',keys:['P1  SPACE / CLICK','P2  ENTER / CLICK']},
  street:{title:'FIGHT NIGHT',tag:'Footwork, blocks, and big punches. Drain the other fighter’s health bar.',kicker:'ARCADE FIGHTER',theme:['#171821','#f7e9c8','#f0bc46','#df536b'],hint:'Move, jump, block, and punch. Best of one.',button:'FIGHT',keys:['P1  WASD + F','P2  ARROWS + ENTER']}
};
const id=new URLSearchParams(location.search).get('game')||document.body.dataset.game||'pong', cfg=G[id]||G.pong;
document.documentElement.style.setProperty('--bg',cfg.theme[0]);document.documentElement.style.setProperty('--panel',cfg.theme[1]);document.documentElement.style.setProperty('--accent',cfg.theme[2]);document.documentElement.style.setProperty('--accent2',cfg.theme[3]);
document.title=`${cfg.title} — Grau Games`;
$('#gameTitle').textContent=cfg.title;$('#gameTag').textContent=cfg.tag;$('#gameKicker').textContent=cfg.kicker;$('#controlHint').textContent=cfg.hint;$('#startButton').textContent=cfg.button;$('#keyP1').textContent=cfg.keys[0];$('#keyP2').textContent=cfg.keys[1];$('#gameName').textContent=cfg.title;
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'), W=1000,H=620; let dpr=1;
function resize(){dpr=Math.min(2,devicePixelRatio||1);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const input={keys:new Set(),edges:new Set(),pointer:[{x:.25,y:.5,down:false},{x:.75,y:.5,down:false}],camera:false};
const pkeys=[['w','a','s','d'],['arrowup','arrowleft','arrowdown','arrowright']];
function edgeFor(n){return n===0?input.edges.has('p1'):input.edges.has('p2')}
function move(n){const k=pkeys[n];return {x:(input.keys.has(k[3])?1:0)-(input.keys.has(k[1])?1:0),y:(input.keys.has(k[2])?1:0)-(input.keys.has(k[0])?1:0)}}
function resetEdges(){input.edges.clear();input.pointer.forEach(p=>p.down=false)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='escape'){if(session.status==='playing')pause();return}if(k==='m'){reset();return}if(!input.keys.has(k)){if(['w','a','s','d','f',' '].includes(k))input.edges.add('p1');if(['arrowup','arrowdown','arrowleft','arrowright','enter'].includes(k))input.edges.add('p2')}input.keys.add(k);if(session.status==='menu')start()});
addEventListener('keyup',e=>input.keys.delete(e.key.toLowerCase()));
function pointerPos(e){const r=canvas.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)}}
canvas.addEventListener('pointermove',e=>{const p=pointerPos(e),n=p.x<.5?0:1;input.pointer[n].x=p.x;input.pointer[n].y=p.y});canvas.addEventListener('pointerdown',e=>{const p=pointerPos(e),n=p.x<.5?0:1;input.pointer[n].x=p.x;input.pointer[n].y=p.y;input.pointer[n].down=true;input.edges.add(`p${n+1}`);if(session.status==='menu')start()});
function ctl(n,dt){const m=move(n),q=input.pointer[n],center=n?.75:.25;const usePointer=Math.abs(m.x)+Math.abs(m.y)===0;const dx=usePointer?(q.x-center)*2:m.x,dy=usePointer?(q.y-.5)*2:m.y;return {x:q.x,y:q.y,dx,dy,action:edgeFor(n)||q.down}}
let session={status:'menu',time:0,score:[0,0],winner:null,state:null};
function newTet(){return {x:4,y:0,shape:pick([[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]]]),tick:0}}
function pipe(){return {x:1.05,gap:rnd(.25,.68),passed:[false,false]}}
function init(){const base={};switch(id){case'pong':base.ball={x:.5,y:.5,vx:pick([-1,1])*.55,vy:rnd(-.35,.35)};break;case'cut':base.targets=[0,1].map(()=>({x:rnd(.18,.42),y:rnd(.23,.65),vy:0,cut:false}));break;case'flappy':base.birds=[.42,.58].map(()=>({y:.5,v:0,score:0,dead:false}));base.pipes=[pipe()];break;case'subway':base.runners=[1,1].map(()=>({lane:1,life:3,score:0}));base.hazards=[];break;case'angry':base.targets=[0,1].map(()=>Array.from({length:5},(_,i)=>({x:.1+(i%3)*.12,y:.28+Math.floor(i/3)*.2,alive:true})));base.aim=[{x:.25,y:.5},{x:.75,y:.5}];break;case'tetris':base.tets=[newTet(),newTet()];base.boards=[0,1].map(()=>Array.from({length:18},()=>Array(10).fill(0)));base.lines=[0,0];break;case'space':base.ships=[.23,.77];base.bullets=[];base.enemies=Array.from({length:12},(_,i)=>({x:.1+(i%6)*.07,y:.16+Math.floor(i/6)*.08,alive:true}));break;case'kart':base.runners=[.25,.75].map(x=>({x,y:0,boost:0,hit:0,score:0}));base.obstacles=[];break;case'whack':base.targets=[null,null];base.spawn=0;break;case'pacman':base.players=[0,1].map(n=>({x:n? .78:.22,y:.82,score:0,life:3}));base.dots=Array.from({length:40},(_,i)=>({x:.08+(i%10)*.093,y:.16+Math.floor(i/10)*.16,side:i%2}));base.ghosts=[{x:.35,y:.4,vx:.2,side:0},{x:.65,y:.4,vx:-.2,side:1}];break;case'doodle':base.players=[0,1].map(()=>({x:.25,y:.72,vy:0,height:0,life:3}));base.platforms=Array.from({length:10},(_,i)=>({x:rnd(.08,.42),y:.82-i*.085,w:rnd(.12,.23),side:0}));base.platforms.push(...Array.from({length:10},(_,i)=>({x:rnd(.58,.86),y:.82-i*.085,w:rnd(.12,.23),side:1})));break;case'crossy':base.players=[0,1].map(()=>({x:.25,y:0,cross:0,life:3}));base.cars=Array.from({length:12},(_,i)=>({x:rnd(0,1),y:.2+(i%4)*.15,v:(i%2?-.22:.22)*(i%3?1:1),side:i%2}));break;case'stack':base.towers=[0,1].map(()=>({blocks:[{x:.25,w:.19,y:.89}],block:{x:.06,w:.19,dir:1},level:0}));break;case'geometry':base.runners=[0,1].map(()=>({y:.88,vy:0,jump:false,dist:0,life:3}));base.spikes=[];break;case'helix':base.players=[0,1].map(()=>({x:.25,depth:0,life:3}));base.rings=Array.from({length:14},(_,i)=>({y:.82-i*.07,gap:rnd(.12,.88)}));break;case'bomber':base.players=[{x:1,y:2,alive:true},{x:7,y:2,alive:true}];base.bombs=[];base.walls=[];for(let y=0;y<5;y++)for(let x=0;x<9;x++)if((x+y)%3===0&&x>1&&x<7)base.walls.push({x,y});break;case'connect':base.boards=[0,1].map(()=>Array.from({length:6},()=>Array(7).fill(0)));base.cols=[3,3];break;case'brawl':base.fighters=[{x:.25,y:.5,hp:5,cool:0},{x:.75,y:.5,hp:5,cool:0}];base.shots=[];break;case'party':base.round=0;base.goal=pick(['TARGET','MATCH','REFLEX']);base.targets=[null,null];base.next=0;break;case'street':base.fighters=[{x:.28,y:.82,hp:100,block:0,attack:0},{x:.72,y:.82,hp:100,block:0,attack:0}];break}session.state=base}
function start(){if(session.status==='playing')return;session={status:'playing',time:0,score:[0,0],winner:null,state:null};init();$('#startButton').textContent='PAUSE MATCH';status('LIVE — make your move')}
function pause(){if(session.status==='playing'){session.status='paused';status('PAUSED — press START to resume')}else if(session.status==='paused'){session.status='playing';status('LIVE — back in the arena')} }
function reset(){session={status:'menu',time:0,score:[0,0],winner:null,state:null};init();$('#startButton').textContent=cfg.button;status('Ready when you are')}
function finish(w){session.status='over';session.winner=w;$('#startButton').textContent='PLAY AGAIN';status(w<0?'DRAW':`PLAYER ${w+1} WINS — press PLAY AGAIN`)}
function status(s){$('#statusLine').textContent=s;$('#scoreP1').textContent=session.score[0];$('#scoreP2').textContent=session.score[1]}
function font(n,b=false){return `${b?'900 ':''}${n}px ${getComputedStyle(document.documentElement).getPropertyValue('--display')||'Arial'}`}
function txt(s,x,y,n=24,color='#fff',align='center'){ctx.save();ctx.font=font(n,true);ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(s,x,y);ctx.restore()}
function box(x,y,w,h,fill,stroke=cfg.theme[1],lw=3){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.strokeRect(x,y,w,h)}}
function circle(x,y,r,fill,stroke=cfg.theme[1]){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function sidePanel(){box(0,0,W,H,cfg.theme[0],null);ctx.strokeStyle='rgba(255,255,255,.13)';ctx.lineWidth=2;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='rgba(255,255,255,.25)';ctx.setLineDash([8,12]);ctx.beginPath();ctx.moveTo(W/2,0);ctx.lineTo(W/2,H);ctx.stroke();ctx.setLineDash([])}
function draw(){sidePanel();switch(id){case'pong':drawPong();break;case'cut':drawCut();break;case'flappy':drawFlappy();break;case'subway':drawSubway();break;case'angry':drawAngry();break;case'tetris':drawTetris();break;case'space':drawSpace();break;case'kart':drawKart();break;case'whack':drawWhack();break;case'pacman':drawPacman();break;case'doodle':drawDoodle();break;case'crossy':drawCrossy();break;case'stack':drawStack();break;case'geometry':drawGeometry();break;case'helix':drawHelix();break;case'bomber':drawBomber();break;case'connect':drawConnect();break;case'brawl':drawBrawl();break;case'party':drawParty();break;case'street':drawStreet();break}if(session.status==='menu'){ctx.fillStyle='rgba(0,0,0,.34)';ctx.fillRect(0,0,W,H);txt(cfg.button,W/2,H*.47,40,cfg.theme[2]);txt('CLICK START OR USE YOUR KEYS',W/2,H*.55,16,cfg.theme[1])}if(session.status==='paused'){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,W,H);txt('PAUSED',W/2,H*.5,48,cfg.theme[2])}if(session.status==='over'){ctx.fillStyle='rgba(0,0,0,.42)';ctx.fillRect(0,0,W,H);txt(session.winner<0?'DRAW':`PLAYER ${session.winner+1} WINS`,W/2,H*.44,42,cfg.theme[2]);txt('PLAY AGAIN TO RUN IT BACK',W/2,H*.54,16,cfg.theme[1])}}
function update(dt){if(session.status!=='playing')return;session.time+=dt;const s=session.state,a=ctl(0,dt),b=ctl(1,dt);switch(id){case'pong':updPong(dt,a,b);break;case'cut':updCut(dt,a,b);break;case'flappy':updFlappy(dt,a,b);break;case'subway':updSubway(dt,a,b);break;case'angry':updAngry(dt,a,b);break;case'tetris':updTetris(dt,a,b);break;case'space':updSpace(dt,a,b);break;case'kart':updKart(dt,a,b);break;case'whack':updWhack(dt,a,b);break;case'pacman':updPacman(dt,a,b);break;case'doodle':updDoodle(dt,a,b);break;case'crossy':updCrossy(dt,a,b);break;case'stack':updStack(dt,a,b);break;case'geometry':updGeometry(dt,a,b);break;case'helix':updHelix(dt,a,b);break;case'bomber':updBomber(dt,a,b);break;case'connect':updConnect(dt,a,b);break;case'brawl':updBrawl(dt,a,b);break;case'party':updParty(dt,a,b);break;case'street':updStreet(dt,a,b);break}if(session.time>60&&session.status==='playing')finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1));status(session.status==='playing'?'LIVE — make your move':$('#statusLine').textContent)}
function norm(v,n){return clamp(v,0,1)*n}
function updPong(dt,a,b){const s=session.state;s.p1y=clamp((s.p1y??.5)+a.dy*dt*.9,.11,.89);s.p2y=clamp((s.p2y??.5)+b.dy*dt*.9,.11,.89);if(a.y!==.5&&Math.abs(a.dy)+Math.abs(a.dx)===0)s.p1y=clamp(a.y,.11,.89);if(b.y!==.5&&Math.abs(b.dy)+Math.abs(b.dx)===0)s.p2y=clamp(b.y,.11,.89);const q=s.ball;q.x+=q.vx*dt;q.y+=q.vy*dt;if(q.y<.06||q.y>.94){q.vy*=-1;q.y=clamp(q.y,.06,.94)}if(q.x<.09&&Math.abs(q.y-s.p1y)<.13&&q.vx<0){q.vx=Math.abs(q.vx)*1.04;q.vy+=rnd(-.15,.15)}if(q.x>.91&&Math.abs(q.y-s.p2y)<.13&&q.vx>0){q.vx=-Math.abs(q.vx)*1.04;q.vy+=rnd(-.15,.15)}if(q.x<-.02){session.score[1]++;q.x=.5;q.y=.5;q.vx=.55;q.vy=rnd(-.3,.3)}if(q.x>1.02){session.score[0]++;q.x=.5;q.y=.5;q.vx=-.55;q.vy=rnd(-.3,.3)}if(session.score.some(v=>v>=7))finish(session.score[0]>=7?0:1)}
function updCut(dt,a,b){const s=session.state;[a,b].forEach((p,n)=>{const t=s.targets[n];t.y+=dt*(.13+n*.02);if(p.action&&Math.abs(p.x-(n?.75:.25))<.28&&Math.abs(p.y-t.y)<.2){session.score[n]++;t.x=rnd(.12,.42);t.y=rnd(.2,.45)}if(t.y>.95){t.y=rnd(.2,.45);t.x=rnd(.12,.42);status(`${n?'P2':'P1'} missed the candy`)}});if(session.time>35)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updFlappy(dt,a,b){const s=session.state;s.birds.forEach((q,n)=>{const p=n?a:b;q.v+=dt*.75;q.y+=q.v*dt;if(p.action)q.v=-.42});let q=s.pipes[0];q.x-=dt*.28;if(q.x<-.1){s.pipes.shift();s.pipes.push(pipe());q=s.pipes[0]}s.birds.forEach((bird,n)=>{if(bird.dead)return;const px=n?.78:.22;if(q.x<px+.04&&q.x+.12>px-.04&&(bird.y<q.gap-.16||bird.y>q.gap+.16)){bird.dead=true;bird.y=.5}if(bird.y<.03||bird.y>.97)bird.dead=true;if(q.x<px&&!q.passed[n]){q.passed[n]=true;bird.score++;session.score[n]=bird.score}});if(s.birds.every(q=>q.dead))finish(s.birds[0].score===s.birds[1].score?-1:(s.birds[0].score>s.birds[1].score?0:1))}
function updSubway(dt,a,b){const s=session.state;s.runners.forEach((r,n)=>{const p=n?b:a;if((p.dx<-.3||input.keys.has(n?'arrowleft':'a'))&&r.lane>0)r.lane=Math.max(0,r.lane-1);if((p.dx>.3||input.keys.has(n?'arrowright':'d'))&&r.lane<2)r.lane=Math.min(2,r.lane+1);r.score+=dt*.5});s.hazards.forEach(h=>h.y+=dt*.35);if(Math.random()<dt*.8)s.hazards.push({side:Math.random()<.5?0:1,lane:Math.floor(rnd(0,3)),y:.02});s.hazards=s.hazards.filter(h=>h.y<1.1);s.hazards.forEach(h=>{if(h.y>.78&&h.y<.94&&s.runners[h.side].lane===h.lane){s.runners[h.side].life--;h.y=2}});s.runners.forEach((r,n)=>{session.score[n]=Math.floor(r.score);if(r.life<=0)finish(n?0:1)});if(session.time>45)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updAngry(dt,a,b){const s=session.state;[a,b].forEach((p,n)=>{s.aim[n].x=clamp(p.x,n?.52:.02,n?.98:.48);s.aim[n].y=clamp(p.y,.08,.92);if(p.action){const t=s.targets[n].find(q=>q.alive&&Math.hypot(q.x-s.aim[n].x,q.y-s.aim[n].y)<.1);if(t){t.alive=false;session.score[n]++;}}});if(s.targets.every(ts=>ts.every(t=>!t.alive)))finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function cells(board){return board.reduce((n,r)=>n+r.filter(Boolean).length,0)}
function updTetris(dt,a,b){const s=session.state;s.tets.forEach((t,n)=>{t.tick+=dt;if(t.tick>.65){t.y++;t.tick=0}const p=n?a:b;if(p.dx<-.3)t.x=Math.max(0,t.x-1);if(p.dx>.3)t.x=Math.min(9-(t.shape[0].length),t.x+1);if(p.action){t.y+=3;lockTet(n)}if(t.y>16)lockTet(n)});function lockTet(n){const t=s.tets[n],bd=s.boards[n];for(let y=0;y<t.shape.length;y++)for(let x=0;x<t.shape[y].length;x++)if(t.shape[y][x]&&bd[t.y+y])bd[Math.min(17,t.y+y)][Math.min(9,t.x+x)]=1;const keep=s.boards[n].filter(r=>r.some(v=>!v));while(keep.length<18)keep.unshift(Array(10).fill(0));s.boards[n]=keep;s.lines[n]+=18-keep.length?1:0;session.score[n]=s.lines[n];s.tets[n]=newTet()} }
function updSpace(dt,a,b){const s=session.state;[a,b].forEach((p,n)=>{s.ships[n]=clamp(s.ships[n]+p.dx*dt*.6,n?.52:.02,n?.98:.48);if(p.action)s.bullets.push({x:s.ships[n],y:.87,v:-.6,side:n})});s.bullets.forEach(b=>b.y+=b.v*dt);s.bullets=s.bullets.filter(b=>b.y>.05);s.bullets.forEach(b=>s.enemies.forEach(e=>{const hit=e.alive&&Math.abs(e.x-b.x)<.04&&Math.abs(e.y-b.y)<.05&&((b.side===0&&e.x<.5)||(b.side===1&&e.x>.5));if(hit){e.alive=false;session.score[b.side]++;b.y=0}}));if(!s.enemies.some(e=>e.alive))finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updKart(dt,a,b){const s=session.state;s.runners.forEach((r,n)=>{const p=n?b:a;r.x=clamp(r.x+p.dx*dt*.45,n?.54:.04,n?.96:.46);r.boost=Math.max(0,r.boost-dt);r.score+=dt*(r.boost?1.6:1);r.hit=Math.max(0,r.hit-dt);if(p.action)r.boost=.8});s.obstacles.forEach(o=>o.y+=dt*.4);if(Math.random()<dt*.9)s.obstacles.push({side:Math.random()<.5?0:1,x:rnd(.08,.42),y:.02});s.obstacles=s.obstacles.filter(o=>o.y<1.1);s.obstacles.forEach(o=>{if(o.y>.77&&o.y<.94&&Math.abs(o.x-s.runners[o.side].x)<.07)s.runners[o.side].hit=.8});s.runners.forEach((r,n)=>session.score[n]=Math.floor(r.score));if(session.time>45)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updWhack(dt,a,b){const s=session.state;s.spawn-=dt;if(s.spawn<=0){const n=Math.random()<.5?0:1;s.targets[n]={x:rnd(n?.56:.06,n?.94:.44),y:rnd(.2,.8),life:1.1,bonus:Math.random()<.18};s.spawn=.55}for(let n=0;n<2;n++){if(s.targets[n]){s.targets[n].life-=dt;const p=n?b:a;if(p.action&&Math.hypot(p.x-s.targets[n].x,p.y-s.targets[n].y)<.12){session.score[n]+=s.targets[n].bonus?3:1;s.targets[n]=null}}}for(let n=0;n<2;n++)if(s.targets[n]?.life<=0)s.targets[n]=null;if(session.time>35)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updPacman(dt,a,b){const s=session.state;s.players.forEach((p,n)=>{const c=n?b:a;p.x=clamp(p.x+c.dx*dt*.45,n?.53:.03,n?.97:.47);p.y=clamp(p.y+c.dy*dt*.45,.08,.92);s.dots=s.dots.filter(d=>{if(d.side!==n)return true;if(Math.hypot(d.x-p.x,d.y-p.y)<.055){session.score[n]++;return false}return true});if(s.ghosts.some(g=>g.side===n&&Math.hypot(g.x-p.x,g.y-p.y)<.04))p.life--});if(s.dots.length===0)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1));if(session.time>50)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updDoodle(dt,a,b){const s=session.state;s.players.forEach((p,n)=>{const c=n?b:a;p.x=clamp(p.x+c.dx*dt*.42,n?.52:.04,n?.96:.46);p.vy+=dt*.72;p.y+=p.vy*dt;if(p.vy>0){const hit=s.platforms.find(o=>o.side===n&&p.x>o.x&&p.x<o.x+o.w&&p.y>.78&&p.y<.9);if(hit){p.vy=-.52;p.height=Math.max(p.height,Math.floor((.9-p.y)*100))}}if(p.y>1.05){p.life--;p.y=.7;p.vy=-.45}session.score[n]=p.height});if(s.players.some(p=>p.life<=0))finish(s.players[0].life<=0?1:0);if(session.time>45)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updCrossy(dt,a,b){const s=session.state;s.players.forEach((p,n)=>{const c=n?b:a;p.x=clamp(p.x+c.dx*dt*.55,n?.52:.02,n?.98:.48);p.y=clamp(p.y+c.dy*dt*.7,0,1);if(p.y<.05){p.cross++;p.y=.92;session.score[n]=p.cross}});s.cars.forEach(c=>{c.x+=c.v*dt;if(c.x<-.1)c.x=1.1;if(c.x>1.1)c.x=-.1});s.players.forEach((p,n)=>s.cars.forEach(c=>{if(c.side===n&&Math.abs(c.x-p.x)<.055&&Math.abs(c.y-(.2+(p.y*.6)))<.07){p.life--;p.y=.92}}));if(s.players.some(p=>p.cross>=5))finish(s.players[0].cross>=5?0:1);if(s.players.some(p=>p.life<=0))finish(s.players[0].life<=0?1:0)}
function updStack(dt,a,b){const s=session.state;s.towers.forEach((t,n)=>{const p=n?b:a;t.block.x+=t.block.dir*dt*.35;if(t.block.x<.05||t.block.x+t.block.w>.45)t.block.dir*=-1;if(p.action){const prev=t.blocks[t.blocks.length-1],left=Math.max(prev.x,t.block.x),right=Math.min(prev.x+prev.w,t.block.x+t.block.w),w=right-left;if(w<.025){finish(n?0:1);return}t.blocks.push({x:left,w,y:.89-t.blocks.length*.07});t.level++;t.block={x:.05,w,dir:t.block.dir};session.score[n]=t.level}});if(s.towers.some(t=>t.level>=10))finish(s.towers[0].level>=10?0:1)}
function updGeometry(dt,a,b){const s=session.state;s.runners.forEach((r,n)=>{const p=n?b:a;r.dist+=dt*.25;const floor=.88;r.vy+=dt*1.2;r.y+=r.vy*dt;if(p.action&&r.y>=floor-.03)r.vy=-.58;const sp=Math.floor(r.dist*4);if(sp%4===3&&r.y>floor-.08)r.life--;session.score[n]=Math.floor(r.dist*10)});if(s.runners.some(r=>r.life<=0))finish(s.runners[0].life<=0?1:0);if(session.time>45)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function updHelix(dt,a,b){const s=session.state;s.players.forEach((p,n)=>{const c=n?b:a;p.x=clamp(p.x+c.dx*dt*.5,n?.54:.04,n?.96:.46);p.depth+=dt*.13;session.score[n]=Math.floor(p.depth*100);const ring=Math.floor(p.depth*14);const gap=s.rings[ring%s.rings.length].gap;if(Math.abs(p.x-gap)>.14&&p.depth%1<.05)p.life--});if(s.players.some(p=>p.life<=0))finish(s.players[0].life<=0?1:0);if(session.time>50)finish(session.score[0]===session.score[1]?-1:(session.score[0]>session.score[1]?0:1))}
function gridPos(p,n){const c=n?input.keys.has('arrowleft'):-input.keys.has('a');return p}
function updBomber(dt,a,b){const s=session.state;s.players.forEach((p,n)=>{const c=n?b:a;const m=move(n);p.x=clamp(p.x+Math.sign(m.x)*dt*4,0,8);p.y=clamp(p.y+Math.sign(m.y)*dt*4,0,4);if(c.action&&!s.bombs.some(q=>q.owner===n))s.bombs.push({x:Math.round(p.x),y:Math.round(p.y),owner:n,t:1.4})});s.bombs.forEach(b=>b.t-=dt);for(const b of s.bombs.filter(q=>q.t<=0)){s.players.forEach((p,n)=>{if(Math.round(p.x)===b.x&&Math.round(p.y)===b.y)p.alive=false});s.bombs=s.bombs.filter(q=>q!==b)}if(s.players.some(p=>!p.alive))finish(s.players[0].alive?0:1)}
function dropDisc(board,col,v){for(let y=5;y>=0;y--)if(!board[y][col]){board[y][col]=v;return y}return -1}
function four(board,v){for(let y=0;y<6;y++)for(let x=0;x<7;x++)if(board[y][x]===v){for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(let k=1;k<4;k++){const xx=x+dx*k,yy=y+dy*k;if(xx>=0&&xx<7&&yy>=0&&yy<6&&board[yy][xx]===v)n++;}if(n>=4)return true}}return false}
function updConnect(dt,a,b){const s=session.state;[a,b].forEach((p,n)=>{const c=n?b:a;const m=move(n);if(m.x<-.2)s.cols[n]=Math.max(0,s.cols[n]-1);if(m.x>.2)s.cols[n]=Math.min(6,s.cols[n]+1);if(c.action){const y=dropDisc(s.boards[n],s.cols[n],1);if(y>=0){session.score[n]++;if(four(s.boards[n],1))finish(n)}}})}
function updBrawl(dt,a,b){const s=session.state;s.fighters.forEach((f,n)=>{const c=n?b:a,m=move(n);f.x=clamp(f.x+m.x*dt*.45,n?.55:.04,n?.96:.46);f.y=clamp(f.y+m.y*dt*.45,.08,.92);f.cool=Math.max(0,f.cool-dt);if(c.action&&f.cool<=0){s.shots.push({x:f.x,y:f.y,vx:n?-0.7:.7,side:n});f.cool=.45}});s.shots.forEach(q=>{q.x+=q.vx*dt;const enemy=s.fighters[1-q.side];if(Math.abs(q.x-enemy.x)<.04&&Math.abs(q.y-enemy.y)<.06){enemy.hp--;session.score[q.side]++;q.x=2}});s.shots=s.shots.filter(q=>q.x>0&&q.x<1);if(s.fighters.some(f=>f.hp<=0))finish(s.fighters[0].hp<=0?1:0)}
function updParty(dt,a,b){const s=session.state;s.next-=dt;if(s.next<=0){s.goal=pick(['TARGET','MATCH','REFLEX']);s.targets=[{x:rnd(.08,.42),y:rnd(.18,.82),c:pick(['#fff','#000','#ff5']),life:1},{x:rnd(.58,.92),y:rnd(.18,.82),c:pick(['#fff','#000','#ff5']),life:1}];s.next=1.4;s.round++}if(s.targets[0]){[a,b].forEach((p,n)=>{if(p.action&&Math.hypot(p.x-s.targets[n].x,p.y-s.targets[n].y)<.13){session.score[n]++;s.targets[n]=null}})}if(session.score.some(v=>v>=7))finish(session.score[0]>=7?0:1)}
function updStreet(dt,a,b){const s=session.state;s.fighters.forEach((f,n)=>{const c=n?b:a,m=move(n);f.x=clamp(f.x+m.x*dt*.35,n?.53:.08,n?.92:.47);f.y=clamp(f.y+m.y*dt*.2,.5,.9);f.block=Math.max(0,f.block-dt);f.attack=Math.max(0,f.attack-dt);if((c.action||input.keys.has(n?'enter':'f'))&&f.attack<=0){f.attack=.55;const e=s.fighters[1-n];if(Math.abs(e.x-f.x)<.18&&e.block<=0){e.hp-=12;session.score[n]++}}});if(s.fighters.some(f=>f.hp<=0))finish(s.fighters[0].hp<=0?1:0)}
function drawPong(){const s=session.state;ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(60,norm(s.p1y,H)-55,18,110);ctx.fillRect(922,norm(s.p2y,H)-55,18,110);circle(norm(s.ball.x,W),norm(s.ball.y,H),13,cfg.theme[2]);txt('FIRST TO 7',W/2,34,16,cfg.theme[1])}
function drawCut(){const s=session.state;for(let n=0;n<2;n++){const t=s.targets[n],cx=(n?.75:.25)*W,tx=cx+(t.x-.3)*260;ctx.strokeStyle=cfg.theme[1];ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(cx,H*.05);ctx.lineTo(tx,norm(t.y,H));ctx.stroke();circle(tx,norm(t.y,H),28,n?cfg.theme[3]:cfg.theme[2]);circle(tx-8,norm(t.y,H)-4,4,'#fff');txt(n?'P2':'P1',cx,H*.95,15,cfg.theme[1])}}
function drawFlappy(){const s=session.state;ctx.fillStyle='rgba(255,255,255,.35)';ctx.fillRect(0,H*.8,W,H*.02);const q=s.pipes[0];box(norm(q.x,W),0,120,norm(q.gap-.17,H),cfg.theme[3],cfg.theme[1],3);box(norm(q.x,W),norm(q.gap+.17,H),120,H,cfg.theme[3],cfg.theme[1],3);s.birds.forEach((b,n)=>{circle(norm(n?.78:.22,W),norm(b.y,H),20,n?cfg.theme[3]:cfg.theme[2]);circle(norm(n?.78:.22,W)+7,norm(b.y,H)-4,4,cfg.theme[1]);txt(String(b.score),norm(n?.78:.22,W),55,20,cfg.theme[1])})}
function drawSubway(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.53:0;for(let i=0;i<3;i++){ctx.strokeStyle='rgba(255,255,255,.35)';ctx.beginPath();ctx.moveTo(x0+30+i*70,100);ctx.lineTo(x0+30+i*70,H);ctx.stroke()}const r=s.runners[n];box(x0+50+r.lane*70,H*.78,42,62,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);txt(`♥ ${r.life}`,x0+96,40,16,cfg.theme[1])}s.hazards.forEach(h=>box((h.side?W*.53:0)+50+h.lane*70,norm(h.y,H),42,44,cfg.theme[1],cfg.theme[3]))}
function drawAngry(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.53:0;txt('PIGS',x0+120,48,18,cfg.theme[1]);s.targets[n].forEach(t=>{if(t.alive)circle(x0+t.x*W*.5,norm(t.y,H),23,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1])});const a=s.aim[n];ctx.strokeStyle=cfg.theme[1];ctx.lineWidth=3;ctx.beginPath();ctx.arc(norm(a.x,W),norm(a.y,H),22,0,Math.PI*2);ctx.stroke()}}
function drawTetris(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.53:0,gw=220,gh=396,cell=22;box(x0+10,80,gw,gh,'rgba(0,0,0,.28)',cfg.theme[1],3);for(let y=0;y<18;y++)for(let x=0;x<10;x++)if(s.boards[n][y][x])box(x0+10+x*cell,80+y*cell,cell,cell,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1],1);const t=s.tets[n];for(let y=0;y<t.shape.length;y++)for(let x=0;x<t.shape[y].length;x++)if(t.shape[y][x])box(x0+10+(t.x+x)*cell,80+(t.y+y)*cell,cell,cell,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1],1);txt(`${s.lines[n]} LINES`,x0+120,510,17,cfg.theme[1])}}
function drawSpace(){const s=session.state;ctx.fillStyle='rgba(255,255,255,.55)';for(let i=0;i<45;i++)ctx.fillRect((i*83)%W,(i*47)%H,2,2);s.enemies.forEach(e=>{if(e.alive)box(norm(e.x,W)-13,norm(e.y,H)-10,26,20,cfg.theme[3],cfg.theme[1],2)});s.ships.forEach((x,n)=>{ctx.beginPath();ctx.moveTo(norm(x,W),H*.9);ctx.lineTo(norm(x,W)-20,H*.95);ctx.lineTo(norm(x,W)+20,H*.95);ctx.closePath();ctx.fillStyle=n?cfg.theme[3]:cfg.theme[2];ctx.fill();ctx.strokeStyle=cfg.theme[1];ctx.stroke()});s.bullets.forEach(b=>box(norm(b.x,W)-3,norm(b.y,H),6,18,cfg.theme[2]))}
function drawKart(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.53:0;ctx.strokeStyle='rgba(255,255,255,.4)';ctx.lineWidth=4;for(let x=30;x<470;x+=60){ctx.beginPath();ctx.moveTo(x0+x,0);ctx.lineTo(x0+x,H);ctx.stroke()}const r=s.runners[n];box(norm(r.x,W),H*.78,40,60,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);txt(`${Math.floor(r.score)}m`,x0+220,44,20,cfg.theme[1])}s.obstacles.forEach(o=>box(norm(o.x,W),norm(o.y,H),34,34,cfg.theme[1],cfg.theme[2]))}
function drawWhack(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.5:0;ctx.strokeStyle=cfg.theme[1];for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(x0+40+i*70,H*.25);ctx.lineTo(x0+40+i*70,H*.82);ctx.stroke()}if(s.targets[n])circle(norm(s.targets[n].x,W),norm(s.targets[n].y,H),s.targets[n].bonus?36:28,s.targets[n].bonus?cfg.theme[2]:cfg.theme[3],cfg.theme[1])}}
function drawPacman(){const s=session.state;ctx.strokeStyle=cfg.theme[2];ctx.lineWidth=14;ctx.strokeRect(35,80,430,430);ctx.strokeRect(535,80,430,430);s.dots.forEach(d=>circle(norm(d.x,W),norm(d.y,H),5,cfg.theme[1],null));s.players.forEach((p,n)=>{circle(norm(p.x,W),norm(p.y,H),20,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);txt(String(p.score),norm(n?.78:.22,W),50,18,cfg.theme[1])});s.ghosts.forEach(g=>circle(norm(g.x,W),norm(g.y,H),17,cfg.theme[3],cfg.theme[1]))}
function drawDoodle(){const s=session.state;s.platforms.forEach(o=>{ctx.fillStyle=o.side?cfg.theme[3]:cfg.theme[2];ctx.fillRect(norm(o.x,W),norm(o.y,H),norm(o.w,W),10)});s.players.forEach((p,n)=>{circle(norm(p.x,W),norm(p.y,H),18,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);txt(`♥${p.life}`,norm(n?.78:.22,W),45,16,cfg.theme[1])})}
function drawCrossy(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.5:0;for(let i=0;i<4;i++){ctx.fillStyle=i%2?'rgba(255,255,255,.05)':'rgba(0,0,0,.08)';ctx.fillRect(x0,H*(.15+i*.15),W*.5,H*.12)}}s.cars.forEach(c=>box(norm(c.x,W),norm(.2+c.y*.6,H),45,24,cfg.theme[2],cfg.theme[1]));s.players.forEach((p,n)=>{circle(norm(p.x,W),norm(.92-p.y*.7,H),18,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);txt(`${p.cross}/5`,norm(n?.75:.25,W),45,17,cfg.theme[1])})}
function drawStack(){const s=session.state;for(let n=0;n<2;n++){const t=s.towers[n],x0=n?W*.53:0;box(x0+35,70,210,430,'rgba(0,0,0,.17)',cfg.theme[1],3);t.blocks.forEach((b,i)=>box(x0+norm(b.x,W*.5),norm(b.y,H),norm(b.w,W*.5),34,i%2?cfg.theme[2]:cfg.theme[3],cfg.theme[1]));box(x0+norm(t.block.x,W*.5),norm(.89-t.blocks.length*.07,H),norm(t.block.w,W*.5),34,cfg.theme[2],cfg.theme[1]);txt(`${t.level}/10`,x0+140,540,22,cfg.theme[1])}}
function drawGeometry(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.53:0;ctx.fillStyle=cfg.theme[1];ctx.fillRect(x0,H*.9,W*.47,8);const r=s.runners[n],x=x0+((r.dist*150)%430);box(x,H* r.y,32,32,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);for(let i=0;i<5;i++){const sx=x0+80+i*75-(r.dist*190%75);ctx.beginPath();ctx.moveTo(sx,H*.9);ctx.lineTo(sx+18,H*.84);ctx.lineTo(sx+36,H*.9);ctx.closePath();ctx.fillStyle=cfg.theme[1];ctx.fill()}txt(`♥${r.life}`,x0+60,46,18,cfg.theme[1])}}
function drawHelix(){const s=session.state;for(let i=0;i<14;i++){const y=H*(.16+i*.07),g=s.rings[i].gap*W;ctx.strokeStyle=i%2?cfg.theme[3]:cfg.theme[2];ctx.lineWidth=16;ctx.beginPath();ctx.arc(W*.25,y,120,0.35,Math.PI*1.65);ctx.stroke();ctx.beginPath();ctx.arc(W*.75,y,120,0.35,Math.PI*1.65);ctx.stroke();ctx.fillStyle=cfg.theme[1];ctx.fillRect(g-35,y-8,70,16)}s.players.forEach((p,n)=>circle(norm(p.x,W),H*.22+((p.depth%1)*H*.12),18,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]))}
function drawBomber(){const s=session.state,cell=50,x0=275,y0=160;for(let y=0;y<5;y++)for(let x=0;x<9;x++)box(x0+x*cell,y0+y*cell,cell,cell,(x+y)%2?'rgba(0,0,0,.08)':'rgba(255,255,255,.08)',cfg.theme[1],1);s.walls.forEach(w=>box(x0+w.x*cell,y0+w.y*cell,cell,cell,cfg.theme[1],cfg.theme[2],2));s.bombs.forEach(b=>circle(x0+b.x*cell+25,y0+b.y*cell+25,17,cfg.theme[2],cfg.theme[1]));s.players.forEach((p,n)=>box(x0+p.x*cell+9,y0+p.y*cell+9,32,32,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1],2))}
function drawConnect(){const s=session.state;for(let n=0;n<2;n++){const x0=n?W*.55:50;box(x0,100,360,300,'rgba(0,0,0,.2)',cfg.theme[2],4);for(let y=0;y<6;y++)for(let x=0;x<7;x++){circle(x0+28+x*50,128+y*45,17,s.boards[n][y][x]?(n?cfg.theme[3]:cfg.theme[2]):cfg.theme[1],cfg.theme[1])}txt(`COLUMN ${s.cols[n]+1}`,x0+180,450,18,cfg.theme[1])}}
function drawBrawl(){const s=session.state;s.fighters.forEach((f,n)=>{circle(norm(f.x,W),norm(f.y,H),27,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1]);box(norm(n?.56:.04,W),35,180,15,'rgba(0,0,0,.3)',cfg.theme[1],2);box(norm(n?.56:.04,W),35,180*(f.hp/5),15,n?cfg.theme[3]:cfg.theme[2],null);txt(`${f.hp} HP`,norm(n?.65:.25,W),70,17,cfg.theme[1])});s.shots.forEach(q=>circle(norm(q.x,W),norm(q.y,H),8,cfg.theme[2],cfg.theme[1]))}
function drawParty(){const s=session.state;txt(`ROUND ${s.round}`,W/2,48,20,cfg.theme[1]);if(s.targets[0]){s.targets.forEach((t,n)=>{if(t)circle(norm(t.x,W),norm(t.y,H),34,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1])})}txt(s.goal,W/2,H*.9,26,cfg.theme[1])}
function drawStreet(){const s=session.state;ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(80,H*.84,840,5);s.fighters.forEach((f,n)=>{const x=norm(f.x,W),y=norm(f.y,H);box(x-30,y-100,60,100,n?cfg.theme[3]:cfg.theme[2],cfg.theme[1],4);if(f.attack>0){ctx.strokeStyle=cfg.theme[2];ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(x+(n?-30:30),y-65);ctx.lineTo(x+(n?-85:85),y-80);ctx.stroke()}box(n?W*.55:W*.05,50,W*.4,18,'rgba(0,0,0,.35)',cfg.theme[1],2);box(n?W*.55:W*.05,50,W*.4*(f.hp/100),18,n?cfg.theme[3]:cfg.theme[2],null)});txt('ROUND 1',W/2,45,18,cfg.theme[1])}
// Optional camera: MediaPipe hand landmarks, loaded only after the player asks.
let cam={running:false,stream:null,video:$('#camVideo'),landmarker:null,last:-1};
async function toggleCamera(){if(cam.running){cam.stream?.getTracks().forEach(t=>t.stop());cam.running=false;$('#cameraButton').classList.remove('active');$('#cameraButton').textContent='CAMERA MODE';$('#cameraDrawer').hidden=true;input.camera=false;return}try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera unavailable');cam.stream=await navigator.mediaDevices.getUserMedia({video:{width:512,height:384},audio:false});cam.video.srcObject=cam.stream;await cam.video.play();$('#cameraDrawer').hidden=false;$('#cameraButton').classList.add('active');$('#cameraButton').textContent='CAMERA ON';input.camera=true;const v=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14');const fs=await v.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');cam.landmarker=await v.HandLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2});toast('Hands ready — use the left and right halves');}catch(e){toast('Camera unavailable — keyboard and pointer controls still work');cam.stream?.getTracks().forEach(t=>t.stop());}}
function cameraTick(now){if(cam.running&&cam.landmarker&&cam.video.currentTime!==cam.last){cam.last=cam.video.currentTime;try{const r=cam.landmarker.detectForVideo(cam.video,now);(r.landmarks||[]).forEach((lm,i)=>{const x=1-lm[8].x,y=lm[8].y,n=x<.5?0:1;input.pointer[n].x=x;input.pointer[n].y=y;input.pointer[n].down=Math.hypot(lm[4].x-lm[8].x,lm[4].y-lm[8].y)<.07})}catch{}}}
function toast(s){const e=$('#toast');e.textContent=s;e.hidden=false;setTimeout(()=>e.hidden=true,3000)}
$('#startButton').addEventListener('click',()=>{if(session.status==='menu'||session.status==='over')start();else pause()});$('#resetButton').addEventListener('click',reset);$('#cameraButton').addEventListener('click',toggleCamera);init();if(id==='space')session.state.enemies.forEach((e,i)=>{e.x=i<6?.1+(i%6)*.06:.56+((i-6)%6)*.06;e.y=.16+Math.floor((i%6)/3)*.08});status('Ready when you are');
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;cameraTick(now);update(dt);draw();resetEdges();requestAnimationFrame(loop)}requestAnimationFrame(loop);
